name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # Har kuni yarim tunda ishga tushadi
  workflow_dispatch:       # Qo'lda ham ishga tushirish mumkin
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Generate github-contribution-grid-snake
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: CyberdineT800
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark

      - name: Push output to `output` branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
